#!/usr/bin/env perl
use strict;
use warnings;

use lib 't';
use helper;
use Test::Deep;

use Genesis qw/load_yaml_file run slurp/;
use_ok 'Genesis::Config';

# Genesis::Config::save converts the config to YAML with `spruce merge`
# and writes its own "---" plus a comment header above the result.
# graft, which many hosts install under the name spruce, prints a
# leading "---" of its own where spruce prints none.  Left in place,
# that second marker turns the header into an empty first document and
# `spruce json` (and so load_yaml_file) refuses to read the file back.
#
# A wrapper spruce on PATH forces the leading marker for merge, so the
# test exercises the failure mode no matter which implementation the
# host has installed.

my $real_spruce = (grep {-x $_} map {"$_/spruce"} split(/:/, $ENV{PATH}))[0];
plan skip_all => "spruce is required to exercise Genesis::Config::save"
	unless $real_spruce;

my $tmp = workdir();
my $fakebin = "$tmp/fakebin";
mkdir $fakebin or die "mkdir $fakebin: $!";
open my $fh, '>', "$fakebin/spruce" or die "create fake spruce: $!";
print $fh <<SH;
#!/bin/bash
# Behave like graft: a merge always starts with a document marker.
if [[ "\$1" == "merge" ]]; then
	out="\$("$real_spruce" "\$@")" || exit \$?
	[[ "\$out" == ---* ]] || echo "---"
	printf '%s\\n' "\$out"
else
	exec "$real_spruce" "\$@"
fi
SH
close $fh;
chmod 0755, "$fakebin/spruce" or die "chmod fake spruce: $!";

subtest 'the fake spruce emits a leading document marker' => sub {
	local $ENV{PATH} = "$fakebin:$ENV{PATH}";
	my ($out, $rc) = run({stderr => 0}, 'echo \'{"a":1}\' | spruce merge --skip-eval -');
	is($rc, 0, "fake spruce merge succeeds");
	like($out, qr/\A---\n/, "fake spruce merge output starts with ---");
};

subtest 'saved config carries exactly one document marker' => sub {
	local $ENV{PATH} = "$fakebin:$ENV{PATH}";

	my $path = "$tmp/repo/.genesis/config";
	my $config = Genesis::Config->new($path, 1);
	$config->set('genesis_version', '3.2.0');
	$config->set('deployment_type', 'bosh');
	$config->set('secrets_provider.type', 'vault');
	$config->save;

	ok(-f $path, "config file was written");
	my @lines = split /\n/, slurp($path);
	my @markers = grep {$_ eq '---'} @lines;
	is(scalar(@markers), 1, "file contains exactly one --- line");
	is($lines[0], '---', "the document marker is the first line");
	like($lines[1], qr/^# This file is generated by Genesis/, "header comment follows the marker");
	like($lines[2], qr/^# Last updated by \S+ on \d{4}-\d\d-\d\d at \d\d:\d\d:\d\d UTC$/, "timestamp comment follows");
	is($lines[3], '', "blank line separates the header from the content");
	isnt($lines[4], '---', "content follows the header directly");

	my ($data, $rc, $err) = load_yaml_file($path);
	is($rc, 0, "load_yaml_file reads the saved config back") or diag($err);
	cmp_deeply($data, {
		genesis_version  => '3.2.0',
		deployment_type  => 'bosh',
		secrets_provider => {type => 'vault'},
	}, "round-tripped contents match what was saved");

	my $reloaded = Genesis::Config->new($path);
	is($reloaded->get('deployment_type'), 'bosh', "Genesis::Config reloads the file it wrote");
};

subtest 'saved config is unchanged when spruce prints no marker' => sub {
	# The stock PATH: under real spruce this is the historical output,
	# under graft it is the same as the wrapped case above.
	my $path = "$tmp/plain/.genesis/config";
	my $config = Genesis::Config->new($path, 1);
	$config->set('genesis_version', '3.2.0');
	$config->save;

	my @lines = split /\n/, slurp($path);
	is(scalar(grep {$_ eq '---'} @lines), 1, "file contains exactly one --- line");
	my ($data, $rc, $err) = load_yaml_file($path);
	is($rc, 0, "load_yaml_file reads the saved config back") or diag($err);
	is($data->{genesis_version}, '3.2.0', "contents survive the round trip");
};

done_testing;
