=head1 NAME

Genesis::Kit::Compiler

=head1 DESCRIPTION

The Compiler class encapsulates all of the rules and logic that go into
compiling a kit source directory into a distributable Genesis Kit tarball.
It includes facilities for validating the kit source, expunging files we
don't wish to distribute (other tarballs, ci/ directories, etc.), and
handles the naming and composition of the Kit archive.

This module is fully object-oriented, and does not export any procedural
functions or package variables.

    use Genesis::Kit::Compiler;

    my $cc = Genesis::Kit::Compiler->new("path/to/kit/src");
    if (!$cc->validate) {
      error "#R{Problems were found with your Kit source.}";
      exit 2;
    }

    my $v = '1.0.9';
    $cc->compile("my-kit", , ".");
    # file will be ./my-kit-1.0.9.tar.gz

=head1 METHODS

=head2 new($root)

Instantiate a new Kit Compiler, for compiling the source found in C<$root>.

=head2 validate()

Validate a Kit by inspecting its source code and defined metadata.

The following validations are performed:

=over

=item 1.

All kits must have a kit.yml with valid YAML in it.

=item 2.

The kit.yml file must provide values for the top-level C<name>, C<author>,
C<homepage>, and C<github> keys.

=item 3.

The C<hooks/> directory must exist.

=item 4.

Any present hooks must be executable files.

=item 5.

If defined, the C<genesis_min_version> value must be a valid semantic
version.

=back

=head2 compile($name, $version, $outdir)

Compiles a kit source directory into a distributable tarball, of the given
version.  Version is specified here, vs. in the kit.yml metadata, to enable
automation of release engineering via tools like Concourse.  Compilation
implciitly calls C<validate()> for you, so you don't need to do so
out-of-band.

The output tarball will be written to C<$outdir/$name-$version.tar.gz>, and
will bundle all files in the archive under the relative path
C<$name-$version/>.

=head2 scaffold($name)

Generates a new kit source directory, populating it with (hopefully!)
helpful scaffolding files for things like kit.yml, hooks, and manifest
fragments.

=head2 CAVEATS

You cannot easily re-use one Kit Compiler to compile a different directory.
Several internal functions cache state that is only valid for a single root
source directory.  In practice this is not an issue, since for the most
part Genesis just uses this for the C<compile-kit> sub-command, which only
deals with a single Kit.

=cut
