=head1 NAME

Genesis::Top

=head1 DESCRIPTION

Several interactions with Genesis have to take place in the context of a
I<root> directory.  Often, this is the something-deployments git repository.

This module abstracts out operations on that root directory, so that other
parts of the codebase can stop worrying about things like file paths, and
instead can carry around a C<Top> context object which handles it for them.

=head1 CONSTRUCTORS

=head2 new($path)

Instantiate a new Top object, pointing at C<$path>.

=head2 create($path, $name, %opts)

Creates a new deployment repository in C<$path>/C<$name>-deployments,
initializes it by creating the C<.genesis/> directory hierarchy, and returns
a new Top object pointing to that root directory.

The following options are currently supported:

=over

=item directory

Override the name of the new directory (which defaults to
C<$name>-deployments).

=back


=head1 METHODS

=head2 link_dev_kit($path)

Creates a symbolic link from C<dev/> to C<$path> (re-interpreted as an
absolute path).  This allows callers to correctly install the link for
Genesis to find a development kit source directory.

=head2 embed($bin)

Embeds the file C<$bin> into C<.genesis/bin/genesis>, and chmods it
properly.  This embedded copy of (probably Genesis) is used by the CI/CD
pipelines to avoid having to stuff versions into docker images.

=head2 download_kit($spec)

Takes a kit spec (name or name/version) and attempts to download the release
matching the spec from Github.

Contact Github, search through the B<genesis-community> organization, and
download the named kit and version (or latest) and stuff it in the
.genesis/kits directory.  This is the magic behind C<genesis download>.

This returns the actual kit name and version that was downloaded (useful when
no version specified or was specified as "latest")

=head2 path([$relative])

Qualifies and returns C<$relative> as an absolute path.

=head2 mkfile($file, [$mode], $contents)

Creates a file, relative to the Top root directory, using C<mkfile_or_fail>.

=head2 mkdir($file, [$mode])

Creates a directory, relative to the Top root directory, using
C<mkfile_or_fail>.

=head2 config()

Parses and returns the Genesis deployments repository configuration, found
in C<$root/.genesis/config>.

=head2 type()

Returns the deployment type of this Genesis root directory, which is used in
naming deployment environments.

=head2 has_dev_kit()

Returns true if the root directory has a so-called I<dev kit>, an uncompiled
directory that contains all of the kit files, for use in buiding and testing
Genesis kits.  The presence or absence of dev kits modifies the behavior of
Genesis substantially.

=head2 compiled_kits()

Returns a two-level hashref, associating kit names to their versions, to
their compiled tarball paths.  For example:

    {
      'bosh' => {
        '0.2.0' => 'root/path/to/bosh-0.2.0.tar.gz',
        '0.2.1' => 'root/path/to/bosh-0.2.1.tgz',
      },
    }

=head2 local_kit_version([$name || $spec, [$version]])

Looks through the list of compiled kits and returns the correct Genesis::Kit
object for the requested name/version combination.  Returns C<undef> if no
kit was found to satisfy the requirements.

If C<$name> is not given (or passed explicitly as C<undef>), this function
will look for the given C<$version> (pursuant to the rules in the following
paragraph), and expect only a single type of kit to exist in .genesis/kits.
If C<$name> is the string "dev", the development kit (in dev/) will be used
if it exists, or no kit will be returned (without checking compiled kits).

If C<$version> is not given (i.e. C<undef>), or is "latest", an analysis of
the named kit will be done to determine the latest version, per semver.

Some examples may help to clarify:

    # find the 1.0 concourse kit:
    $top->local_kit_version(concourse => '1.0');

    # find the latest concourse kit:
    $top->local_kit_version(concourse => 'latest');

    # find the latest version of whatever kit we have
    $top->local_kit_version(undef, 'latest');

    # find version 2.0 of whatever kit we have
    $top->local_kit_version(undef, '2.0');

    # find using kit spec string
    $top->local_kit_version('concourse/1.0.3');

    # explicitly use the dev/ kit
    $top->local_kit_version('dev');

    # use whatever makes the most sense.
    $top->local_kit_version();

Note that if you omit C<$name>, there is a semantic difference between
passing C<$version> as "latest" and not passing it (or passing it as
C<undef>, explicitly).  In the former case (version = "latest"), the latest
version of the singleton compiled kit is returned.  In the latter case,
C<local_kit_version> will check for a dev/ directory and use that if available.

=head2 load_env($name)

Loads a new Genesis::Env object, named $name, from the root directory.
This wraps a call to Genesis::Env->load().

=head2 has_env($name)

Returns true if an environment by the given name exists under the repo.

=head2 create_env($name, $kit, %opts)

Creates a new Genesis::Env object, which will go through provisioning.
This wraps a call to Genesis::Env->create().

=cut
